### ISSUE TITLE
cannot access archive 'zlog-build-deps_0.7.0-1_all.deb': No such file or directory

### ISSUE THREAD

**Issue by DeadFishw** [cruzdb/zlog#392]
I got this message while trying to run ./install-deps.sh. I am using WSL ubuntu

**Comment by DeadFishw** [comment]
Complete message: Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Fetched 336 kB in 3s (125 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
devscripts is already the newest version (2.20.2ubuntu2).
equivs is already the newest version (2.2.0).
git is already the newest version (1:2.25.1-1ubuntu3.8).
The following packages were automatically installed and are no longer required:
  libfwupdplugin1 libxmlb1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
/tmp/tmp.85LnuZfC26 ~/zlog
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
/usr/bin/fakeroot: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
Error in the build process: exit status 1
dpkg: error: cannot access archive 'zlog-build-deps_0.7.0-1_all.deb': No such file or directory
mk-build-deps: dpkg --unpack failed

**Comment by dotnwat** [comment]
Hey @DeadFishw. I haven't tired building zlog on WSL. It looks like the `fakeroot` usage syntax has changed. You might have better luck building with an older verison of Ubuntu in docker.

```
/usr/bin/fakeroot: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
```

Happy to merge fixes if you get it working.

**Comment by DeadFishw** [comment]
I just went on cmake and making and it seems to be no problem continuing.

**Comment by DeadFishw** [comment]
The problem is solved by entering sudo update-alternatives --set fakeroot /usr/bin/fakeroot-tcp

**Comment by dotnwat** [comment]
thanks @DeadFishw !
