### ISSUE TITLE
zlog_init: Initializing zlog with a path to a directory doesn't result in an error

### ISSUE THREAD

**Issue by iancuivasciuc** [cruzdb/zlog#393]
If we try to initialize zlog with a wrong path to a file, we will get an error.
Instead, if we try to initialize zlog with a wrong path which points to a valid directory, we won't get any error.
It would be the same as if we tried to initialized it with an empty file.

**Comment by dotnwat** [comment]
Thanks for the report. Happy to accept PRs that fix any issues.

**Comment by iancuivasciuc** [comment]
I made a mistake. I wanted to create an issue to another zlog project.
